<?xml version="1.0"?>
<robot name="hdt_arm" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- Gazebo -->
    <xacro:include filename="$(find hdt_description)/urdf/hdt_angler_a_gazebo.xacro" />

    <!-- motor and transmition -->
    <xacro:include filename="$(find hdt_description)/urdf/hdt_angler_a_transmission.xacro" />

    <!-- camera sensor -->
    <xacro:include filename="$(find hdt_description)/urdf/hdt_angler_a_sensor.xacro" />

    <xacro:macro name="hdt_serial_arm" params="namespace hardware_interface ">

        <xacro:hdt_transmission_macro namespace="${namespace}" hardware_interface="${hardware_interface}" />
        <xacro:hdt_gazebo_macro namespace="${namespace}"/>
        <xacro:hdt_sensor_macro namespace="${namespace}"/>

        <!-- constants -->
        <xacro:property name="M_PI" value="3.1415926535897931"/>
        <xacro:property name="mass" value="0.107" />

        <xacro:property name="drive_length" value="0.047"/>
        <xacro:property name="a35_length" value="0.03855"/>
        
        <!--xacro:property name="drive_offset" value="0.033"/-->
        <xacro:property name="tube_diameter" value="0.0515"/>
        <xacro:property name="pedestal_height" value="0.03859"/>
        <xacro:property name="pedestal_boss" value="0.0448"/>
        <xacro:property name="drive_offset" value="0.02455"/>
        <xacro:property name="pincer_offset" value="0.0415"/>
        
        <xacro:property name="a24_proximal_length" value="0.353"/>
        <xacro:property name="a24_distal_length" value="0.344"/>
        <xacro:property name="a35_proximal_length" value="0.308"/>
        <xacro:property name="a35_distal_length" value="0.19"/>
        
        <!-- materials -->
        <material name="black1">
            <color rgba="${200/255} ${200/255} ${200/255} 1.0"/>
        </material>

        <material name="grey1">
            <color rgba="${64/255} ${64/255} ${64/255} 1.0"/>
        </material>
        
        <material name="yellow1">
            <color rgba="${240/255} ${224/255} ${64/255} 1.0"/>
        </material>

        <!-- default inertia -->
        <xacro:macro name="default_inertia">
            <inertia
            ixx="0.05" ixy="0.01" ixz="0.01"
            iyy="0.05" iyz="0.01"
            izz="0.05"/>
        </xacro:macro>

        <!-- segment 0 -->
        <!-- <link name="${namespace}/base_link"/> -->

        <!-- pedestal -->
        <!-- <joint name="${namespace}/pedestal_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <parent link="${namespace}/base_link"/>
            <child link="${namespace}/pedestal_link"/>
        </joint> -->

        <link name="${namespace}/pedestal_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H026994 - A35 M-2 PEDESTAL ASSY - SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H026994 - A35 M-2 PEDESTAL ASSY - SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>
            
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

        <!-- drive 1 -->
        <joint name="${namespace}/drive1_joint" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="60.0" lower="${-2*M_PI}" upper="${2*M_PI}" velocity="${M_PI/4}"/>
            <origin xyz="0 0 ${(pedestal_boss+a35_length)}" rpy="0 0 ${-M_PI/2}"/>
            <parent link="${namespace}/pedestal_link"/>
            <child link="${namespace}/drive1_link"/>
            <dynamics damping="0.7" friction="0.0"/>
        </joint>

        <link name="${namespace}/drive1_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>
            
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

        <!-- drive 2 -->
        <joint name="${namespace}/drive2_joint" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="60.0" lower="${-M_PI/2}" upper="${M_PI/2}" velocity="${M_PI/4}"/>
            <origin xyz="${drive_offset+drive_length} 0 0" rpy="0 -${M_PI/2} 0"/>
            <parent link="${namespace}/drive1_link"/>
            <child link="${namespace}/drive2_link"/>
            <dynamics damping="0.7" friction="0.0"/>
        </joint>

        <link name="${namespace}/drive2_link">
            <collision>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>
            
            <inertial>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

        <!-- humerus -->
        <joint name="${namespace}/humerus_joint" type="fixed">
            <origin xyz="${a35_proximal_length/2+drive_offset} 0 0" rpy="0 0 0" />
            <parent link="${namespace}/drive2_link"/>
            <child link="${namespace}/humerus_link"/>
        </joint>

        <link name="${namespace}/humerus_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024847 - A35 M-2 PROXIMAL TUBE ASSY - SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024847 - A35 M-2 PROXIMAL TUBE ASSY - SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

        <!-- elbow -->
        <joint name="${namespace}/elbow_joint" type="fixed">
            <origin xyz="${a35_proximal_length/2+drive_offset} 0 0" rpy="0 0 0"/>
            <parent link="${namespace}/humerus_link"/>
            <child link="${namespace}/elbow_link"/>
        </joint>

        <link name="${namespace}/elbow_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>
            
            <inertial>
                <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>
        
        <!-- drive 3 -->
        <joint name="${namespace}/drive3_joint" type="revolute">
            <axis xyz="0 0 1"/>
        <!-- position limits to match parameter settings on actuator -->
            <limit effort="60.0" lower="-4.49" upper="1.35" velocity="${M_PI/4}"/>
            <origin xyz="0 0 ${drive_length+drive_offset}" rpy="0 0 0"/>
            <parent link="${namespace}/elbow_link"/>
            <child link="${namespace}/drive3_link"/>
            <dynamics damping="0.7" friction="0.0"/>
        </joint>

        <link name="${namespace}/drive3_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>
            
            <inertial>
                <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

        <!-- drive 4 -->
        <joint name="${namespace}/drive4_joint" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="60.0" lower="${-2*M_PI}" upper="${2*M_PI}" velocity="${M_PI/4}"/>
            <origin xyz="0 ${a35_distal_length/2 + drive_length} 0" rpy="-${M_PI/2} 0 0"/>
            <parent link="${namespace}/drive3_link"/>
            <child link="${namespace}/drive4_link"/>
            <dynamics damping="0.7" friction="0.0"/>
        </joint>

        <link name="${namespace}/drive4_link">
            <collision>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024848 - A35 M-2 DISTAL TUBE ASSY - SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024848 - A35 M-2 DISTAL TUBE ASSY - SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>
        
        <!-- wrist -->
        <joint name="${namespace}/wrist_joint" type="fixed">
            <origin xyz="0 0 ${a35_distal_length/2 + drive_offset + 0.01}" rpy="${M_PI/2} -${M_PI/2} ${M_PI}"/>
            <parent link="${namespace}/drive4_link"/>
            <child link="${namespace}/wrist_link"/>
        </joint>

        <link name="${namespace}/wrist_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>
            
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>
        
        <!-- drive 5 -->
        <joint name="${namespace}/drive5_joint" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="60.0" lower="${-M_PI*2}" upper="${M_PI*2}" velocity="${M_PI/4}"/>
            <origin xyz="0 0 -${drive_length + drive_offset}" rpy="${M_PI} 0 0"/>
            <parent link="${namespace}/wrist_link"/>
            <child link="${namespace}/drive5_link"/>
            <dynamics damping="0.7" friction="0.0"/>
        </joint>

        <link name="${namespace}/drive5_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 ${M_PI/2} ${M_PI}"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 ${M_PI/2} ${M_PI}"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024840 - A35 M-2 DRIVE MODULE, SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

            <!-- drive 6 -->
        <joint name="${namespace}/drive6_joint" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="60.0" lower="${-M_PI*2}" upper="${M_PI*2}" velocity="${M_PI/4}"/>
            <origin xyz="${drive_length + pincer_offset} 0 0" rpy="0 ${M_PI/2} 0"/>
            <parent link="${namespace}/drive5_link"/>
            <child link="${namespace}/drive6_link"/>
            <dynamics damping="0.7" friction="0.0"/>
        </joint>

        <link name="${namespace}/drive6_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024842 - A35 M-2 PINCER ASSY - SHAREABLE, UNDERWATER.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 ${M_PI/2} -${M_PI/2}"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H024842 - A35 M-2 PINCER ASSY - SHAREABLE, UNDERWATER.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>
            
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

        <!-- Pincers -->
        <joint name="${namespace}/pincer_joint" type="revolute">
            <!-- <hdt id="10" kmin="75" kmax="150" inertia="0.075"/>		 -->
            <axis xyz="0 0 1"/>
            <limit effort="60.0" lower="-0.2" upper="0.9" velocity="0.5"/>
            <origin xyz="0.0135 0 0.0375" rpy="-${M_PI/2} -${M_PI/2} 0"/> 
            <parent link="${namespace}/drive6_link"/>
            <child link="${namespace}/pincer_link"/>
            <dynamics damping="0.7" friction="0.0"/>
        </joint>


        <link name="${namespace}/pincer_link">
            <collision>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H022927 - A35 PINCER FINGER, LONG, OVERMOLD ASSY - SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H022927 - A35 PINCER FINGER, LONG, OVERMOLD ASSY - SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

        <!-- EE 2 -->
        <!-- THIS IS THE SECOND PINCER, NEEDS TO MOVE EQUAL BUT OPPOSITE AS PINCER 1 -->
        <joint name="${namespace}/pincer_joint2" type="revolute">
        <!--<hdt id="10b" kmin="75" kmax="150" inertia="0.075"/>-->
            <axis xyz="0 0 1"/>
            <origin xyz="-0.0135 0 0.0375" rpy="-${M_PI/2} -${M_PI/2} ${M_PI}"/> 
            <parent link="${namespace}/drive6_link"/>
            <child link="${namespace}/pincer_link2"/>
            <calibration rising="0.0"/>
            <dynamics damping="0.7" friction="0.0"/>
            <limit effort="60.0" lower="-0.2" upper="1" velocity="0.5"/>
            <mimic joint="${namespace}/pincer_joint" multiplier="1" offset="0.0"/>
        </joint>


        <link name="${namespace}/pincer_link2">
            <collision>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <geometry>
                <mesh filename="package://hdt_angler_description/meshes/H022927 - A35 PINCER FINGER, LONG, OVERMOLD ASSY - SHAREABLE.STL"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
                <geometry>
                    <mesh filename="package://hdt_angler_description/meshes/H022927 - A35 PINCER FINGER, LONG, OVERMOLD ASSY - SHAREABLE.STL"/>
                </geometry>
                <material name="black1"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <xacro:default_inertia />
            </inertial>
        </link>

        <!-- endpoint -->
        <joint name="${namespace}/endpoint_joint" type="fixed">
            <origin xyz="0 0 0.1" rpy="${M_PI/2} ${-M_PI/2} 0"/>
            <parent link="${namespace}/drive6_link"/>
            <child link="${namespace}/endpoint_link"/>
        </joint>

        <link name="${namespace}/endpoint_link">
        </link>
    </xacro:macro>
</robot>

